### ISSUE TITLE
plug in will not work in some browsers

### ISSUE THREAD

**Issue by forresme** [Dani3lSun/apex-plugin-dropzone#10]
At my work the company standard browsers are IE 11 and Firefox 45.0.2.  I have access to Chrome browser but it is not considered a company standard browser and the applications I develop need to be able to run on IE and Firefox.

The drag/drop and file upload feature work, but the paste does not work in IE 11 and Firefox 45.0.2.  It does work on Chrome.  On my personal PC's that run Microsoft Edge and Firefox 50.0.2 it works like a charm.  This plug in is perfect for a project I am currently working on.  I would like to work with my company to find a way to be able to use this functionality but wanted to find out from you if we need to be on Edge/latest Firefox, or is there a setting in the IE 11/Firefox 45.0.2 browsers that I need to have changed?

**Comment by Dani3lSun** [comment]
Unfortunately this behavior is normal, because only a few modern browsers support the clipboard API with files & DataUrls.

In the time developing this plugin only Chrome supported that feature. As of today I can say I only was successful on Chrome and Firefox >= 50...
(Safari & Safari Technology Preview, IE11, Edge 25.10586.672.0, Firefox < 50 was not successful).

Which is good, 1 Browser more that supports that feature, maybe 2 if you say you was successful with Edge, too...

As in the description of the plugin said, only a few very modern browsers support that feature, hopefully more to come...

**Comment by forresme** [comment]
Thank you for confirming this for me so I will know what to ask the desktop services team for!  Love the plug in!

Regards,
Melinda E. Forrester
Sr. Systems Developer, TIP Governance, EPO
Technology, Innovation and Performance (TIP)

PPD
Melinda.Forrester@ppdi.com
<mailto:Melinda.Forrester@ppdi.com>www.ppdi.com<http://www.ppdi.com/>

PPD LSS Yellow Belt

[cid:image002.png@01D0CB6E.A9660160]
