### ISSUE TITLE
File not uploading in Custom Table.

### ISSUE THREAD

**Issue by munirhub** [Dani3lSun/apex-plugin-dropzone#22]
Hi Daniel,

After getting your demos I was able to run the dropzone without any issues, when it is selected as APRX_COLLECTION. However, While I was trying to insert into custom table getting the error"Database Error During Upload". Could you please shade light on this. Thanks, Munir. 

![1](https://cloud.githubusercontent.com/assets/26344238/23829199/93e20336-0715-11e7-82b4-70aa5c9ed796.jpg)

![2](https://cloud.githubusercontent.com/assets/26344238/23829201/9b51f1ee-0715-11e7-9bea-5d78eab8ab02.jpg)

**Comment by Dani3lSun** [comment]
Hey @munirhub 
your plugin settings look fine. I think the reason why it is not working, is a missing Before Insert Trigger  for the Primary Key Column of your table.
Could this be? Do you have a trigger on your table?
Thus Dropzone Plugin doesn´t generate PK Values, it requires a Trigger to do it...
If you look at the Help Tab in PageDesigner when clicking the "Storage Type" Attribute of Dropzone, when you will see a little description...
A Trigger ould look like this:
```
create or replace trigger file_table_trigger before insert on file_table
for each row
begin
  select file_table_seq.nextval into :new.file_id from dual;
end;
```
<img width="1379" alt="page_designer" src="https://cloud.githubusercontent.com/assets/698942/23830599/23cb817c-070f-11e7-92f6-92d7e44d48ec.png">

**Comment by munirhub** [comment]
Hi Daniel,

Yes, I have the trigger which fired before insert data. Anyway, I have found another alternative which you have posted in previous issues, inserting data from a dynamic action from APEX_COLLECTIONS. 

Another issue I 'm facing. While upload multiple images into dropzone it is saving data in database as soon as upload finished. But If I want to remove any file then I can do it from dropzone. However, File still exists in database. I saw another dynamic action in your PLUGIN. But not sure How to delete record from both Dropzone and Database custom table.  

Anyway, Thanks for your great support and response and also for your signature DEMOS. Hoping to get Scereenshoots also.

**Comment by Dani3lSun** [comment]
Hi @munirhub 
if you analyze the Database JSON response you will see the real error message (ORA-...) instead of "Database error during file upload". Open Chrome Developer Tools and go to Network Tab. Then drop a file into dropzone and let you show the details from the wwv_flow.show Call. See screenshot:
<img width="1679" alt="dropzone_2" src="https://cloud.githubusercontent.com/assets/698942/23830941/8d1539c8-0716-11e7-8969-5007dee72041.png">
The second behavior is normal I think, if you choose APEX Collection when the integrated delete function only can delete files from this collection. But if you just inserted it into your own table (from this collection). Dropzone can´t know that...

Daniel

**Comment by munirhub** [comment]
Daniel,

Another great tips to catch the error. Actually since I was  not getting any ora- .. code thats why could not trace the cause. you are RIGHT! Though  I had trigger that time while I was testing there was an invalid state. That's why it was  trying to insert null value in the PK filed. I have reproduced the error by disabling trigger. 

And now Custom table are working perfectly removing data from both dropzone and database.:)

Thanks for your great afford and time for me. Its really a great tools which will boost the development of Oracle Apex developer. 

![100](https://cloud.githubusercontent.com/assets/26344238/23831027/a881049a-0742-11e7-837b-a271a0439f10.jpg)

**Comment by munirhub** [comment]
One more thing In my mind. Does all your plugins will work in mobile application?

**Comment by Dani3lSun** [comment]
Great that you solved the problem!
If it is >= APEX 5 it should work on mobile too, maybe it is listed under the "unsupported" plugins, because I didn´t check the mobile checkbox in the plugin settings:
<img width="1484" alt="create___edit_plug-in" src="https://cloud.githubusercontent.com/assets/698942/23831144/446ea42a-071b-11e7-8be7-98a9d9978a5b.png">
