### ISSUE TITLE
Plugin Not showing in ORDS

### ISSUE THREAD

**Issue by moinsultan** [Dani3lSun/apex-plugin-dropzone#28]
Dear Developer , i am going to install dropzone plugin in apex 5.1 
ORDS 3.0.3 / Tomcat 7 / Apache 2.4 / Linux x64
when i create region with dropzone plugin its showing nothing.
please help me to run this plugin.

Thanks 
Moin Sultan

**Comment by Dani3lSun** [comment]
Hi @moinsultan 
it is likely that the necessary JS/CSS files of the plugin are not loaded, because they are not found...
If you open your Browser Console, do you see some "404 Not Found" error messages?

If so, please check if you have edited the plugins file prefix to some server side path and check if the plugin files are correctly located there.
If you have not edited the file prefix, so you just imported the plugin and nothing else, I would say that something is wrong with your server configuration, please check the APEX installation guide, especially the part about static files.

**Comment by moinsultan** [comment]
thanks  @Dani3lSun 
I added my JS/CSS files path so its working now. 

Thanks.
