### ISSUE TITLE
Display Message changes not being applied

### ISSUE THREAD

**Issue by forresme** [Dani3lSun/apex-plugin-dropzone#29]
I changed the Display Message in Custom Attributes in the Create/Edit Plug-in screen.  The display message did not change when running the application.  I also tried adding a new plug in region to my page after changing the message and the new region still had the original message as well.
![capture1](https://user-images.githubusercontent.com/24457901/28968407-6e9f772e-78e5-11e7-94b3-dcaa421f72f5.PNG)
![capture2](https://user-images.githubusercontent.com/24457901/28968408-6ea391e2-78e5-11e7-8443-d0e195200187.PNG)

APEX 5.03, Firefox 54, IE 11, Chrome

**Comment by Dani3lSun** [comment]
Hi @forresme 
please don´t edit the plugin attributes directly because the changes are lost if you import an updated version of the plugin. Instead edit the application wide plugin settings under Shared Components --> Component Settings --> Dropzone
<img width="1553" alt="component_defaults" src="https://user-images.githubusercontent.com/698942/28984131-b9be72b0-795c-11e7-80c5-2eb64a1e77f3.png">
