### ISSUE TITLE
Accented characters are not decoded correctly

### ISSUE THREAD

**Issue by nydn** [Dani3lSun/apex-plugin-dropzone#39]
### Expected behavior
Changing the default messages in Component Settings should work with accented characters, like in older versions.
This is from v2.1.0:
![screenshot_20180129_105743](https://user-images.githubusercontent.com/17320899/35513105-d9d5126a-04f9-11e8-9dbf-b4c475684d93.png)

### Actual behavior
Unicode characters are displayed incorrectly.
This is from the same application on the same page and region, with v2.2.2:
![screenshot_20180129_105402](https://user-images.githubusercontent.com/17320899/35513135-f1972f46-04f9-11e8-9087-e33293dfa78a.png)

### APEX version (4.2.6 / 5.0.3)

5.1.1

### Used web server / version and platform (ORDS 3.0.3 / Tomcat 7 / Apache 2.4 / Linux x64)

ORDS3.0.9 / Tomcat 8 / Apache 2.4 / Linux x64

### Used web browser / version and platform (Chrome 48 Mac / Firefox 44 Windows)
Firefox 58 Linux

**Comment by Dani3lSun** [comment]
Hey @nydn 
you are correct...I changed the escaping from *apex_escape.html* to *apex_escape.json* since 2.2.x version:
https://github.com/Dani3lSun/apex-plugin-dropzone/commit/013caa66ba5fd23513979b81caad2e075fb77c8c#diff-183e72408fe211a2ff6cc5e3b4fbfd18
I will fix this issue in the upcoming release!
Thanks for reporting this!

**Comment by Dani3lSun** [comment]
FYI: There is now a new version available that should fix that error...
https://github.com/Dani3lSun/apex-plugin-dropzone/releases/tag/v.2.2.3

**Comment by nydn** [comment]
Thank you,new version works as intended!
