### ISSUE TITLE
Antivirus Check?

### ISSUE THREAD

**Issue by JacoFourie** [Dani3lSun/apex-plugin-dropzone#56]
I am sorry to ask here but nobody else seems to know. We need to scan uploaded files for viruses.
We have configured ICAP on ORDS using Sophos SAVDI. But it is not working. It seems we need to be able to set the service that we have configured on the SAVDI side or change the SAVDI service to that of what Apex is expecting. Do you by any change know how to set-up ICAP ?

We know that SAVDI is working as we tested it using the c-icap-client to upload a test virus file.

**Comment by Dani3lSun** [comment]
Hey @JacoFourie 
sorry I'm not really familiar with this kind of virus scans...As you're saying that you configured it with ORDS, does it work with standard APEX file inputs?

I would definitely choose the "normal" upload method instead of "chunked", thus there the file is not splitted into 1mb chunkes which are base64 encoded...I bet a virus scan engine wouldn't recognize viruses in that encoded chunks...
The normal upload methods sends the file as is to the server using multipart/formData POST

**Comment by JacoFourie** [comment]
@Dani3lSun thanks for coming back to me about this. How do you check for viruses in files being uploaded into Apex if you say you dont use the ICAP method? Let say you develop an app that you open up to the internet where people will upload CVs to apply for a job. You don't know what files will come into your DB and you need to make sure it is stopped before it gets to the DB. We have installed your plug-in and we see this error if we enable ICAP on ORDS. 

![image](https://user-images.githubusercontent.com/17771641/49220012-a23c8f80-f3dd-11e8-89bc-38c161368a57.png)


I know this is not an issue with your plug-in. was just hoping that seeing you work with files a lot you would know how to do the ICAP part.
