### ISSUE TITLE
Large File Upload - Tomcat

### ISSUE THREAD

**Issue by bcoville** [Dani3lSun/apex-plugin-dropzone#6]
Hi - 

Initially, any file over 2mb, failed.  

Changed Tomcat AJP Connector as described in docs.  

Didn't help.

Changed HTTP Connector with same maxPostSize= settings as AJP connector.  Over 2mb worked nicely.

Good work!  Nice little tool.

**Comment by Dani3lSun** [comment]
Hi @bcoville 
great that it works!
Yeah the readme only describes it for AJP connector, simply because I use Tomcat with AJP connector and in front of it a Apache web server. If you directly connect to Tomcat via HTTP than you have to edit the HTTP connector of it, I will change the docs to better understand that!
