### ISSUE TITLE
Accepted file types - does not accept item name or substitution

### ISSUE THREAD

**Issue by jeffreykemp** [Dani3lSun/apex-plugin-dropzone#9]
### Expected behavior

Accepted File Types attribute should be able to be set to the name of an item, or a substitution variable (page or application item).
### Actual behavior

Accepted File Types attribute appears to be interpreted literally.
### Steps to reproduce the issue
1. Set Accepted File Types to something like P1_MIMETYPE_LIST
2. Set P1_MIMETYPE_LIST to a valid value, e.g. "application/pdf"
3. Drop a file.
   Regardless of file type, the dropzone refuses to accept any file type.
### APEX version (4.2.6 / 5.0.3)

5.0.3
### Used web server / version and platform (ORDS 3.0.3 / Tomcat 7 / Apache 2.4 / Linux x64)

ORDS 3.03
### Used web browser / version and platform (Chrome 48 Mac / Firefox 44 Windows)

Chrome 53 on Windows 7

**Comment by jeffreykemp** [comment]
I've gotten this working on my system for substitution variables by adding this to the plugin PL/SQL:

`l_accepted_files := apex_plugin_util.replace_substitutions(l_accepted_files,false);`

However, it would be preferable if this could be taken at runtime from the item, so I can change the accepted types dynamically - if possible.

**Comment by Dani3lSun** [comment]
Hi @jeffreykemp 
good idea! The only thing you have to do to get this working is e.g your approach in PL/SQL or simply change the setting "Substitute Attribute Values" to Yes in the plugin settings:
<img width="1097" alt="create___edit_plug-in" src="https://cloud.githubusercontent.com/assets/698942/19717652/f6b7c6e6-9b61-11e6-84df-449bf1afbfaa.png">
After that you can write & P1_MIMETYPE_LIST. in the Accepted Mimetypes field or every other field.
Changing it dynamically is not possible, because the whole dropzone with all parameters is rendered at page load...Maybe I can refresh the complete dropzone after one parameter changed...Have to investigate into this, I come back to you!;)

**Comment by jeffreykemp** [comment]
That's great, thanks heaps. I've tried it with the Substitute Attribute Values set on and it works.

I've worked around the lack of dynamic refresh by setting my "file type" list item to "Redirect and Set Value" so that the page is refreshed.

**Comment by Dani3lSun** [comment]
In Version 1.9.6 and 2.0.0 "Substitute Attribute Values" is now per default set to "Yes". Thus Dropzone needs some information at render time its not easy to re-set them dynamically...
